version: '2'
services:
  app:
    build: .
    depends_on:
      - db
    image: "freija/recontent"
    volumes:
      - "./data:/data:ro"
  db:
    image: mongo:3.0.2
    volumes:
      - "./data/db:/data/db"
    command: ["mongod", "--smallfiles"]
# Add these for testing
#  console:
#    build: tools/console
#  curler:
#    build: tools/curler
